version: '3.1'

networks:
  mysql:

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./etc/mysql.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/data

  app:
    build: .
    networks:
      - mysql
    ports:
      - 8000:80
    volumes:
      - ./app:/app
      - ./etc/apache.conf:/opt/docker/etc/httpd/conf.d/custom.conf
      - ./etc/php.ini:/opt/docker/etc/php/php.ini
    environment:
      PHP_DISPLAY_ERRORS: 1

  maildev:
    image: djfarrelly/maildev
    ports:
      - 8025:80

